# Generated by Django 5.2.4 on 2025-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="receipe/aman"),
        ),
    ]
