# Generated by Django 4.2.23 on 2025-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0002_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="receipe/"),
        ),
    ]
